/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "aetxsindfrqpkcuhaiot"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFldHhzaW5kZnJxcGtjdWhhaW90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NjgwNTQsImV4cCI6MjA5MDA0NDA1NH0.N_galb5J-bU8aG0le_LSEkysqpnXHqGAl-uiAOICnHM"